test: Use a docker image for chrome
Pulls in browserless/chrome docker image
to have chrome pre-installed. I'm having
a lot of trouble with the PROTOCOL_TIMEOUT
error during lhci autorun, which is still
unresolved by Lighthouse (it's the #1
issue on the GoogleChrome/lighthouse
repo).

diff --git a/.github/workflows/lighthouse-ci.yaml b/.github/workflows/lighthouse-ci.yaml
--- a/.github/workflows/lighthouse-ci.yaml
+++ b/.github/workflows/lighthouse-ci.yaml
@@ -4,6 +4,15 @@ jobs:
   lhci:
     name: Lighthouse CI
     runs-on: ubuntu-latest
+    container:
+      image: browserless/chrome
+      options: --user root
+      env:
+        NODE_ENV: development
+      ports:
+        - 80
+      volumes:
+        - /docker_volume
     steps:
       - uses: actions/checkout@v1
       - name: Use Node.js 18.x
@@ -11,11 +20,13 @@ jobs:
         with:
           node-version: 18.x
       - name: npm ci
+        run: npm ci
+      - name: Run Lighthouse CI
         run: |
-          npm ci
-      - name: run Lighthouse CI
-        run: |
-          sudo apt install chromium
           npm install -g @lhci/cli@0.11.x
           npm run build
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+          lhci autorun \
+            --only-categories=accessibility,best-practices \
+            --collect.settings.chromeFlags="--no-sandbox --disable-gpu" \
+            --disable-dev-shm-usage \
+            --disable-storage-reset || echo "LHCI failed!"
